### ISSUE TITLE
latent z partition and layer modulation

### ISSUE THREAD

**Issue by yedvvard** [FutureXiang/soda#1]
Hi FutureXiang,
In the SODA paper, the convolutional UNet have 2m + 1 activation layers h_i. The author partition the latent vector z into m + 1 sections, and use each z_i to modulate the respective pair or layers (h_i, h_{2m−i}). Do you seem to have used the entire latent vector z in each decoder layer in your implementation, or did I make a mistake?
![image](https://github.com/FutureXiang/soda/assets/26924516/19197497-9b0f-4586-b21e-f06acad27248)

![image](https://github.com/FutureXiang/soda/assets/26924516/005b43c0-0406-443f-874d-c4c80726ad6d)

**Comment by FutureXiang** [comment]
Hi,
This feature has not been implemented, because there are some unclear implementation details which I find quite confusing in the paper.
For example, the typical diffusion UNet (e.g. ADM) does not have a "symmetric" structure. Each decoder stages often have **one more** residual blocks than their encoder stage counterparts (Please see [EDM UNet code](https://github.com/NVlabs/edm/blob/62072d2612c7da05165d6233d13d17d71f213fee/training/networks.py#L309C46-L309C46) and [EDM2 Figure 15 in Appendix B](https://arxiv.org/pdf/2312.02696.pdf)).
Therefore, the so-called $(h_i, h_{2m-i})$ symmetric correspondence needs to be clarified. Maybe I'll do some test or wait for the official implementation to come out.

Moreover, according to my understanding, the Layer Modulation strategy mainly contributes to representation disentanglement and attribute manipulation, while it doesn't affect linear probe recognition much.

**Comment by yedvvard** [comment]
Hi,
Thank you for your reply! wait for your new implementation.

**Comment by jsrdcht** [comment]
> Hi, This feature has not been implemented, because there are some unclear implementation details which I find quite confusing in the paper. For example, the typical diffusion UNet (e.g. ADM) does not have a "symmetric" structure. Each decoder stages often have **one more** residual blocks than their encoder stage counterparts (Please see [EDM UNet code](https://github.com/NVlabs/edm/blob/62072d2612c7da05165d6233d13d17d71f213fee/training/networks.py#L309C46-L309C46) and [EDM2 Figure 15 in Appendix B](https://arxiv.org/pdf/2312.02696.pdf)). Therefore, the so-called ( h i , h 2 m − i ) symmetric correspondence needs to be clarified. Maybe I'll do some test or wait for the official implementation to come out.
> 
> Moreover, according to my understanding, the Layer Modulation strategy mainly contributes to representation disentanglement and attribute manipulation, while it doesn't affect linear probe recognition much.

Based on the ablation experiment in Table 1 of the paper, modulation has a significant impact on linear probe performance.

**Comment by jsrdcht** [comment]
> Hi, This feature has not been implemented, because there are some unclear implementation details which I find quite confusing in the paper. For example, the typical diffusion UNet (e.g. ADM) does not have a "symmetric" structure. Each decoder stages often have **one more** residual blocks than their encoder stage counterparts (Please see [EDM UNet code](https://github.com/NVlabs/edm/blob/62072d2612c7da05165d6233d13d17d71f213fee/training/networks.py#L309C46-L309C46) and [EDM2 Figure 15 in Appendix B](https://arxiv.org/pdf/2312.02696.pdf)). Therefore, the so-called ( h i , h 2 m − i ) symmetric correspondence needs to be clarified. Maybe I'll do some test or wait for the official implementation to come out.
> 
> Moreover, according to my understanding, the Layer Modulation strategy mainly contributes to representation disentanglement and attribute manipulation, while it doesn't affect linear probe recognition much.

Based on the ablation experiment in Table 1 of the paper, modulation has a significant impact on linear probe performance.
